### ISSUE TITLE
error starting on centos

### ISSUE THREAD

**Issue by tomammon** [Akkadius/glass-isc-dhcp#1]
Hi, 

After what appears to be a successful install, I get the following error when trying start glass:

[root@home glass-isc-dhcp]# npm start

> dhcpd-glass@0.0.0 start /opt/glass-isc-dhcp
> node ./bin/www

/opt/glass-isc-dhcp/app.js:673
let transporter = nodemailer.createTransport({
    ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/glass-isc-dhcp/bin/www:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0

perhaps it has something to do with my version of node.js? Here's the version of node and of the packages that I have installed. It's a centos 6.9 server.

[root@home glass-isc-dhcp]# node --version
v0.10.48

[root@home glass-isc-dhcp]# rpm -qa | grep node
nodejs-boom-0.4.2-2.el6.noarch
nodejs-sha-1.2.1-1.el6.noarch
nodejs-opener-1.3.0-7.el6.noarch
nodejs-glob-3.2.6-1.el6.noarch
nodejs-http-signature-0.10.0-3.el6.noarch
nodejs-which-1.0.5-8.el6.noarch
nodejs-promzard-0.2.0-6.el6.noarch
nodejs-init-package-json-0.0.10-1.el6.noarch
nodejs-npm-registry-client-0.2.28-3.el6.noarch
nodejs-fstream-0.1.24-1.el6.noarch
nodejs-retry-0.6.0-5.el6.noarch
nodejs-forever-agent-0.5.0-1.el6.noarch
nodejs-ctype-0.5.3-3.el6.noarch
nodejs-proto-list-1.2.2-5.el6.noarch
nodejs-ini-1.1.0-3.el6.noarch
nodejs-cryptiles-0.2.2-1.el6.noarch
nodejs-packaging-7-1.el6.noarch
nodejs-archy-0.0.2-8.el6.noarch
nodejs-tunnel-agent-0.3.0-1.el6.noarch
nodejs-0.10.48-3.el6.x86_64
nodejs-hoek-0.9.1-1.el6.noarch
nodejs-nopt-2.1.2-1.el6.noarch
nodejs-github-url-from-git-1.1.1-2.el6.noarch
nodejs-chmodr-0.1.0-4.el6.noarch
nodejs-aws-sign-0.3.0-1.el6.noarch
nodejs-editor-0.0.4-2.el6.noarch
nodejs-fstream-ignore-0.0.7-1.el6.noarch
nodejs-npmconf-0.1.2-1.el6.noarch
nodejs-mkdirp-0.3.5-3.el6.noarch
nodejs-osenv-0.0.3-5.el6.noarch
nodejs-once-1.1.1-5.el6.noarch
nodejs-hawk-1.0.0-1.el6.noarch
nodejs-npm-user-validate-0.0.3-1.el6.noarch
nodejs-assert-plus-0.1.4-1.el6.noarch
nodejs-minimatch-0.2.12-2.el6.noarch
nodejs-combined-stream-0.0.4-3.el6.noarch
nodejs-asn1-0.1.11-3.el6.noarch
nodejs-inherits-2.0.0-4.el6.noarch
nodejs-lru-cache-2.3.0-3.el6.noarch
nodejs-npmlog-0.0.4-1.el6.noarch
nodejs-sntp-0.2.4-1.el6.noarch
nodejs-oauth-sign-0.3.0-1.el6.noarch
nodejs-devel-0.10.48-3.el6.x86_64
nodejs-sigmund-1.0.0-5.el6.noarch
nodejs-delayed-stream-0.0.5-5.el6.noarch
nodejs-rimraf-2.2.2-1.el6.noarch
nodejs-block-stream-0.0.7-1.el6.noarch
nodejs-chownr-0.0.1-9.el6.noarch
nodejs-cmd-shim-1.1.0-3.el6.noarch
nodejs-lockfile-0.4.2-1.el6.noarch
nodejs-mute-stream-0.0.4-1.el6.noarch
nodejs-json-stringify-safe-5.0.0-1.el6.noarch
nodejs-read-package-json-1.1.3-1.el6.noarch
nodejs-uid-number-0.0.3-7.el6.noarch
nodejs-request-2.25.0-3.el6.noarch
nodejs-graceful-fs-2.0.0-2.el6.noarch
nodejs-mime-1.2.11-1.el6.noarch
nodejs-qs-0.6.6-3.el6.noarch
nodejs-node-uuid-1.4.1-1.el6.noarch
nodejs-form-data-0.1.1-1.el6.noarch
nodejs-slide-1.1.5-1.el6.noarch
nodejs-abbrev-1.0.4-6.el6.noarch
nodejs-child-process-close-0.1.1-2.el6.noarch
nodejs-cookie-jar-0.3.0-1.el6.noarch
nodejs-config-chain-1.1.7-1.el6.noarch
nodejs-tar-0.1.18-1.el6.noarch
nodejs-read-1.0.5-1.el6.noarch
nodejs-read-installed-0.2.4-1.el6.noarch
node-gyp-0.10.6-2.el6.noarch
nodejs-semver-2.1.0-1.el6.noarch
nodejs-ansi-0.2.1-1.el6.noarch
nodejs-normalize-package-data-0.2.1-1.el6.noarch
nodejs-async-0.2.10-1.el6.noarch
nodejs-fstream-npm-0.1.5-1.el6.noarch

**Comment by Akkadius** [comment]
Yes I would definitely first look at updating your node version, there should be instructions on their site for getting updated

**Comment by tomammon** [comment]
What version of node is the minimum I should shoot for?

**Comment by Akkadius** [comment]
5.4.2 minimum as posted in the readme.

Now that I am at a PC, here is a link to get you started:

https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

**Comment by tomammon** [comment]
Thanks for the link, that was helpful and it got me a little further ahead, but still no dice. Also, there is no mention of a version in the readme, you may want to include that. I got a different error when I tried to npm install with node.js version 6.11.4 installed. But I'm thinking it will be easier just to set up on debian and match your environment more closely, so I think I'll try going that route. I'll include some output here (below) if you decide to try to make this work on centos in the future. Thanks for the code, it looks way cool!

[root@home glass-isc-dhcp]# npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
dhcpd-glass@0.0.0 /opt/glass-isc-dhcp
├─┬ always-tail@0.2.0
│ └── debug@0.7.4
├─┬ always-tail2@1.0.0
│ └── debug@0.7.4
├── basic-auth@1.1.0
├─┬ body-parser@1.17.2
│ ├── bytes@2.4.0
│ ├── content-type@1.0.4
│ ├── debug@2.6.7
│ ├── depd@1.1.1
│ ├─┬ http-errors@1.6.2
│ │ └── inherits@2.0.3
│ ├── iconv-lite@0.4.15
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.4.0
│ ├─┬ raw-body@2.2.0
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.17
│     └── mime-db@1.30.0
├─┬ cookie-parser@1.4.3
│ ├── cookie@0.3.1
│ └── cookie-signature@1.0.6
├─┬ debug@2.6.9
│ └── ms@2.0.0
├─┬ express@4.15.5
│ ├─┬ accepts@1.3.4
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├── finalhandler@1.0.6
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.5
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.4.0
│ ├── qs@6.5.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.6
│ │ ├── destroy@1.0.4
│ │ └── mime@1.3.4
│ ├── serve-static@1.12.6
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├── utils-merge@1.0.0
│ └── vary@1.1.2
├─┬ express-ipfilter@0.3.1
│ ├── ip@1.1.5
│ ├── lodash@3.10.1
│ └─┬ range_check@1.4.0
│   ├── ip6@0.0.4
│   └── ipaddr.js@1.2.0
├─┬ forever@0.15.3
│ ├─┬ cliff@0.1.10
│ │ ├── colors@1.0.3
│ │ └── eyes@0.1.8
│ ├── clone@1.0.2
│ ├── colors@0.6.2
│ ├─┬ flatiron@0.4.3
│ │ ├─┬ broadway@0.3.6
│ │ │ ├── cliff@0.1.9
│ │ │ └── winston@0.8.0
│ │ ├── director@1.2.7
│ │ ├── optimist@0.6.0
│ │ └─┬ prompt@0.2.14
│ │   ├─┬ read@1.0.7
│ │   │ └── mute-stream@0.0.7
│ │   └── revalidator@0.1.8
│ ├─┬ forever-monitor@1.7.1
│ │ ├─┬ chokidar@1.7.0
│ │ │ ├─┬ anymatch@1.3.2
│ │ │ │ ├─┬ micromatch@2.3.11
│ │ │ │ │ ├─┬ arr-diff@2.0.0
│ │ │ │ │ │ └── arr-flatten@1.1.0
│ │ │ │ │ ├── array-unique@0.2.1
│ │ │ │ │ ├─┬ braces@1.8.5
│ │ │ │ │ │ ├─┬ expand-range@1.8.2
│ │ │ │ │ │ │ └─┬ fill-range@2.2.3
│ │ │ │ │ │ │   ├── is-number@2.1.0
│ │ │ │ │ │ │   ├── isobject@2.1.0
│ │ │ │ │ │ │   └─┬ randomatic@1.1.7
│ │ │ │ │ │ │     ├─┬ is-number@3.0.0
│ │ │ │ │ │ │     │ └── kind-of@3.2.2
│ │ │ │ │ │ │     └── kind-of@4.0.0
│ │ │ │ │ │ ├── preserve@0.2.0
│ │ │ │ │ │ └── repeat-element@1.1.2
│ │ │ │ │ ├─┬ expand-brackets@0.1.5
│ │ │ │ │ │ └── is-posix-bracket@0.1.1
│ │ │ │ │ ├── extglob@0.3.2
│ │ │ │ │ ├── filename-regex@2.0.1
│ │ │ │ │ ├─┬ kind-of@3.2.2
│ │ │ │ │ │ └── is-buffer@1.1.5
│ │ │ │ │ ├─┬ object.omit@2.0.1
│ │ │ │ │ │ ├─┬ for-own@0.1.5
│ │ │ │ │ │ │ └── for-in@1.0.2
│ │ │ │ │ │ └── is-extendable@0.1.1
│ │ │ │ │ ├─┬ parse-glob@3.0.4
│ │ │ │ │ │ ├── glob-base@0.3.0
│ │ │ │ │ │ └── is-dotfile@1.0.3
│ │ │ │ │ └─┬ regex-cache@0.4.4
│ │ │ │ │   └─┬ is-equal-shallow@0.1.3
│ │ │ │ │     └── is-primitive@2.0.0
│ │ │ │ └─┬ normalize-path@2.1.1
│ │ │ │   └── remove-trailing-separator@1.1.0
│ │ │ ├── async-each@1.0.1
│ │ │ ├── glob-parent@2.0.0
│ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ └── binary-extensions@1.10.0
│ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ └── is-extglob@1.0.0
│ │ │ └─┬ readdirp@2.1.0
│ │ │   ├─┬ readable-stream@2.3.3
│ │ │   │ ├── core-util-is@1.0.2
│ │ │   │ ├── isarray@1.0.0
│ │ │   │ ├── process-nextick-args@1.0.7
│ │ │   │ ├── string_decoder@1.0.3
│ │ │   │ └── util-deprecate@1.0.2
│ │ │   └── set-immediate-shim@1.0.1
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.8
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ ps-tree@0.0.3
│ │   └─┬ event-stream@0.5.3
│ │     └── optimist@0.2.8
│ ├─┬ nconf@0.6.9
│ │ ├── async@0.2.9
│ │ ├── ini@1.3.4
│ │ └── optimist@0.6.0
│ ├─┬ nssocket@0.5.3
│ │ ├── eventemitter2@0.4.14
│ │ └── lazy@1.0.11
│ ├── object-assign@3.0.0
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.1
│ ├─┬ prettyjson@1.2.1
│ │ ├── colors@1.1.2
│ │ └── minimist@1.2.0
│ ├─┬ shush@1.0.0
│ │ ├─┬ caller@0.0.1
│ │ │ └─┬ tape@2.3.3
│ │ │   ├── deep-equal@0.1.2
│ │ │   ├── defined@0.0.0
│ │ │   ├── jsonify@0.0.0
│ │ │   ├── resumer@0.0.0
│ │ │   └── through@2.3.8
│ │ └── strip-json-comments@0.1.3
│ ├── timespan@2.3.0
│ ├─┬ utile@0.2.1
│ │ ├── async@0.2.10
│ │ ├── deep-equal@1.0.1
│ │ ├── i@0.3.6
│ │ ├── ncp@0.4.2
│ │ └─┬ rimraf@2.6.2
│ │   └─┬ glob@7.1.2
│ │     ├── fs.realpath@1.0.0
│ │     ├─┬ inflight@1.0.6
│ │     │ └── wrappy@1.0.2
│ │     └── once@1.4.0
│ └─┬ winston@0.8.3
│   ├── cycle@1.0.3
│   ├── isstream@0.1.2
│   ├── pkginfo@0.3.1
│   └── stack-trace@0.0.10
├── humanize@0.0.9
├─┬ jade@1.11.0
│ ├── character-parser@1.2.1
│ ├─┬ clean-css@3.4.28
│ │ ├─┬ commander@2.8.1
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.1
│ ├── commander@2.6.0
│ ├─┬ constantinople@3.0.2
│ │ └── acorn@2.7.0
│ ├─┬ jstransformer@0.0.2
│ │ ├── is-promise@2.1.0
│ │ └─┬ promise@6.1.0
│ │   └── asap@1.0.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ transformers@2.1.0
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.1
│ │ └─┬ uglify-js@2.2.5
│ │   ├── optimist@0.3.7
│ │   └── source-map@0.1.43
│ ├─┬ uglify-js@2.8.29
│ │ ├── source-map@0.5.7
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.10.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@2.1.0
│ │   │ ├─┬ center-align@0.1.3
│ │   │ │ ├─┬ align-text@0.1.4
│ │   │ │ │ ├── longest@1.0.1
│ │   │ │ │ └── repeat-string@1.6.1
│ │   │ │ └── lazy-cache@1.0.4
│ │   │ ├── right-align@0.1.3
│ │   │ └── wordwrap@0.0.2
│ │   ├── decamelize@1.2.0
│ │   └── window-size@0.1.0
│ ├── void-elements@2.0.1
│ └─┬ with@4.0.3
│   ├── acorn@1.2.2
│   └── acorn-globals@1.0.9
├─┬ jsonfile@3.0.1
│ └── graceful-fs@4.1.11
├─┬ morgan@1.8.2
│ ├── debug@2.6.8
│ └── on-headers@1.0.1
├── nodemailer@4.1.3
├─┬ serve-favicon@2.4.5
│ └── safe-buffer@5.1.1
├─┬ slack-node@0.1.8
│ └─┬ requestretry@1.12.2
│   ├── extend@3.0.1
│   ├── lodash@4.17.4
│   ├─┬ request@2.83.0
│   │ ├── aws-sign2@0.7.0
│   │ ├── aws4@1.6.0
│   │ ├── caseless@0.12.0
│   │ ├─┬ combined-stream@1.0.5
│   │ │ └── delayed-stream@1.0.0
│   │ ├── forever-agent@0.6.1
│   │ ├─┬ form-data@2.3.1
│   │ │ └── asynckit@0.4.0
│   │ ├─┬ har-validator@5.0.3
│   │ │ ├─┬ ajv@5.2.3
│   │ │ │ ├── co@4.6.0
│   │ │ │ ├── fast-deep-equal@1.0.0
│   │ │ │ ├── json-schema-traverse@0.3.1
│   │ │ │ └── json-stable-stringify@1.0.1
│   │ │ └── har-schema@2.0.0
│   │ ├─┬ hawk@6.0.2
│   │ │ ├── boom@4.3.1
│   │ │ ├─┬ cryptiles@3.1.2
│   │ │ │ └── boom@5.2.0
│   │ │ ├── hoek@4.2.0
│   │ │ └── sntp@2.0.2
│   │ ├─┬ http-signature@1.2.0
│   │ │ ├── assert-plus@1.0.0
│   │ │ ├─┬ jsprim@1.4.1
│   │ │ │ ├── extsprintf@1.3.0
│   │ │ │ ├── json-schema@0.2.3
│   │ │ │ └── verror@1.10.0
│   │ │ └─┬ sshpk@1.13.1
│   │ │   ├── asn1@0.2.3
│   │ │   ├── bcrypt-pbkdf@1.0.1
│   │ │   ├── dashdash@1.14.1
│   │ │   ├── ecc-jsbn@0.1.1
│   │ │   ├── getpass@0.1.7
│   │ │   ├── jsbn@0.1.1
│   │ │   └── tweetnacl@0.14.5
│   │ ├── is-typedarray@1.0.0
│   │ ├── json-stringify-safe@5.0.1
│   │ ├── oauth-sign@0.8.2
│   │ ├── performance-now@2.1.0
│   │ ├── qs@6.5.1
│   │ ├── stringstream@0.0.5
│   │ ├─┬ tough-cookie@2.3.3
│   │ │ └── punycode@1.4.1
│   │ ├── tunnel-agent@0.6.0
│   │ └── uuid@3.1.0
│   └── when@3.7.8
└─┬ ws@3.2.0
  ├── async-limiter@1.0.0
  └── ultron@1.1.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[root@home glass-isc-dhcp]# npm start

> dhcpd-glass@0.0.0 start /opt/glass-isc-dhcp
> node ./bin/www

cat: /etc/hostname: No such file or directory
child_process.js:515
    throw err;
    ^

Error: Command failed: cat /etc/hostname
cat: /etc/hostname: No such file or directory

    at checkExecSyncError (child_process.js:472:13)
    at execSync (child_process.js:512:13)
    at Object.<anonymous> (/opt/glass-isc-dhcp/app.js:99:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 2.6.32-696.3.2.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dhcpd-glass@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dhcpd-glass@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dhcpd-glass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dhcpd-glass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dhcpd-glass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/glass-isc-dhcp/npm-debug.log
[root@home glass-isc-dhcp]# node --version
v6.11.4

**Comment by Akkadius** [comment]
Hey Tom. It is on the badge at the very top.

I do plan on getting redhat based distros tested, for right now I’ve only tested on Ubuntu / Debian

Thanks for checking it out!
