### ISSUE TITLE
Device Chart missing

### ISSUE THREAD

**Issue by isadp** [Akkadius/glass-isc-dhcp#12]
Hi,
while everything is working fine there are two little issues:

The "Device Chart" graphic is not showing up.
In "Active Leases" I cant search for IP addresses or blocks.

Tested browsers are Chromium and Firefox.

**Comment by Akkadius** [comment]
Hoping to have some time in the next few weeks here and I can take a look

**Comment by kiji310** [comment]
The same issues as Device Chart missing. 
Resolved. It was necessary to open port 8080 at firewall.

Me too.In "Active Leases" I cant search for IP addresses or blocks.
I do not know the solution about this issues.

**Comment by Akkadius** [comment]
There was an issue as well where unidentified devices would not show up on these charts at all, any unidentified MAC OUI's will get sent to `N/A` category. This should be resolved and is independent of websockets

![image](https://user-images.githubusercontent.com/3319450/44074365-e786a014-9f5d-11e8-8849-f71c7c28929e.png)
