### ISSUE TITLE
Support for websocket proxy

### ISSUE THREAD

**Issue by computergeek125** [Akkadius/glass-isc-dhcp#16]
I'm working on getting this behind a TLS terminator (nginx) that I already have running on this server.  I noticed a recent update allows for the HTTP port number to be configured, however, I do not see an option to configure the websocket port server-side.  

My end goal is to configure the system to listen to ws:// on 3001, and have nginx listen for wss:// on 8443.  I'll update this with my progress.

**Comment by Akkadius** [comment]
Sounds good @computergeek125 - as I've noted in another issue my recent job change has taken up my bandwidth to clean address peoples requests. I plan to sit down and hammer out my list for glass soon

**Comment by Akkadius** [comment]
This is now possible, someone submitted a pull request to do part of this, I added endpoints and the client support to do the other

`"ws_port": 8080`

My apologies for the wait, very busy as of late
