### ISSUE TITLE
bin/dhcpd-pools is x86 only

### ISSUE THREAD

**Issue by trogper** [Akkadius/glass-isc-dhcp#18]
I'd like to use glass-isc-dhcp on a raspberry pi, but there are some x86 elf binaries.
I propose detecting architecture on install and copying/linking appropriate binaries

**Comment by Akkadius** [comment]
You will have to build `dhcpd-pools` as instructed in the readme for your architecture. Once compiled, copy it to the bin directory in place of the existing pre-compiled directory.

**Comment by trogper** [comment]
I found out that `dhcpd-pools` is also available in apt, but in current raspbian it's an older version not supporting -A switch, so I compiled it, installed and symlinked. Would you be interested in providing this binary also for ARM?
