### ISSUE TITLE
Loss of Service Control after installing cron job

### ISSUE THREAD

**Issue by Rico1801** [Akkadius/glass-isc-dhcp#2]
After adding the prescribed line in root's crontab, the service starts on reboot, however, the service controls do not work and I was unable to save edits to the dhcp.conf file.

glass-error.log file contained:
`/bin/sh: 1: service: not found`

and the DHCP Config page showed:
`/bin/sh: 1: dhcpd: not found`

I was able to correct this by adding the absolute path `/usr/sbin/` before the service command in ./routes/dhcp_start_stop_restart.js on lines 52, 56, 60

`dhcp_exec = execSync('/usr/sbin/service isc-dhcp-server stop && sleep 1');`
`dhcp_exec = execSync('/usr/sbin/service isc-dhcp-server start');`
`dhcp_exec = execSync('/usr/sbin/service isc-dhcp-server restart && sleep 1');`

AND

Adding the abs path before the dhcpd command in ./routes/dhcp_config_save.js on line 18
`exec('/usr/sbin/dhcpd -t -cf ./syntax_verify_config > verify_output 2> verify_output', function(err, stdout, stderr)`

**Comment by Akkadius** [comment]
What distro is this?

**Comment by Rico1801** [comment]
Ubuntu 16.04

**Comment by Akkadius** [comment]
This thought went through my head as I was implementing things, that I
should absolute to avoid path issues.

Thanks for pointing this out, I’ll go ahead and make fixes when I’m back to
a PC

**Comment by Akkadius** [comment]
Addressed in https://github.com/Akkadius/glass-isc-dhcp/commit/7ac8c91cd16b811d33998636aca16c8ac256d5c9

Thanks for reporting, should be good to go now
