### ISSUE TITLE
Include in config not supported

### ISSUE THREAD

**Issue by NightFlame** [Akkadius/glass-isc-dhcp#30]
I run two dhcpd (on two servers) in failover. Glass installed on primary server. Primary functions of glass works fine (view, read config, monitoring, restart, api).

My dhcpd config splitted by subnets for easy sync on secondary server, for ex.:
`include "/etc/dhcp/dhcpd.d/subnet01.conf";`

**Comment by Akkadius** [comment]
I knew this would be a want, but given the very small amount of time Glass was whipped up for, editing config files was not the primary desire for my needs at the time so I left this as a stretch. I have another issue open requesting this same thing so when time permits or someone implements it I will leave that issue open under label `enhancement`

**Comment by leifnel** [comment]
I would second this issue, as I also have two servers in failover.


I only have a main config, which are rsync'ed from master to slave, and an `include "/etc/dhcp/dhcpd.failover"; `

This file exists on both servers, but contains the different settings for master and slave.

It would be nice if this include could be accepted 
It need not be parsed, as the server runs perfectly fine without it, just in standalone mode.
