### ISSUE TITLE
amount of writes

### ISSUE THREAD

**Issue by bartgrefte** [Akkadius/glass-isc-dhcp#38]
I'm running Debian configured as a router from an USB flash drive, since USB flash drives do not come with wear leveling (that I know of ) the amount of writes needs to be limited.

Judging from the "Install Glass (as root)" part, Glass doesn't save logs in /var/log which is running in ramdisk.

How much writing does this program actually do?

**Comment by Akkadius** [comment]
Hey @bartgrefte the app is only displaying informational based logs from the server (Glass) itself, I would say that its not that much for actual writing but that is a relative measure
