### ISSUE TITLE
Update of OUI Table

### ISSUE THREAD

**Issue by tibmeister** [Akkadius/glass-isc-dhcp#77]
The bin/oui_table.txt file is in a very specific format, not the standard one from the IEEE.  As such, I wrote a very quick and dirty parser through CRONTAB to download the updated file, then parse the file into a new oui_table.txt file.

wget http://standards-oui.ieee.org/oui.txt -O /usr/local/etc/oui.txt 2>&1
cat /usr/local/etc/oui.txt | grep '(base 16)' | sed 's/     //g' | sed 's/\t//g' | sed 's/(base 16)/:::/g' > /opt/glass-isc-dhcp/bin/oui_table.txt 2>&1

Would be nice if either the parser used the format from the IEEE (http://standards-oui.ieee.org/oui.txt) or could just download and update the oui_table.txt file itself.

**Comment by Akkadius** [comment]
That's what this script is for https://github.com/Akkadius/glass-isc-dhcp/blob/master/bin/dhcp_utility.pl
