### ISSUE TITLE
Vendor table empty

### ISSUE THREAD

**Issue by ghost** [Akkadius/glass-isc-dhcp#91]
The vendow table is always empty. Leases are for HP, Samsung, iPhone. Is there a way to troubleshout this?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34521956/128497331-46b9088d-dccd-438c-b859-f1fd2550ddb6.png)

**Comment by madtempest** [comment]
This is what the bin\dhcp_utility.pl script is for.

To use it, you need to run bin\dhcp_utility.pl --leases-file /path/to/your/leasefile --parse
