### ISSUE TITLE
Error forever missing

### ISSUE THREAD

**Issue by Plainbroke** [Akkadius/glass-isc-dhcp#96]
I have tried over and over to do the "sudo npm install forever -g"  so that forever would be installed and quit making the GUI stop.  
Any Ideas would be appreciated...

/bin/sh: 1: ./bin/dhcpd-pools: Permission denied
child_process.js:674
    throw err;
    ^

Error: Command failed: ./bin/dhcpd-pools -c /etc/dhcp/dhcpd.conf -l /var/lib/dhcp/dhcpd.leases -f j -A -s e
/bin/sh: 1: ./bin/dhcpd-pools: Permission denied

DO I HAVE TO INSTALL POOLS ???

npm ERR! code 1
npm ERR! path /opt/glass-isc-dhcp
npm ERR! command failed
npm ERR! command sh -c node ./bin/www

./glass_start.sh: line 3: /usr/bin/forever: No such file or directory

**Comment by Krystian-Zak** [comment]
Try "/opt/glass-isc-dhcp/node_modules/forever/bin/forever" path instead "/usr/bin/forever"

crontab:
@reboot cd /opt/glass-isc-dhcp && /opt/glass-isc-dhcp/node_modules/forever/bin/forever --minUptime 10000 --spinSleepTime 10000 -a -o ./logs/glass-process.log -e ./logs/glass-error.log ./bin/www

**Comment by Plainbroke** [comment]
Will do thank you..
